---
  - name: Install dnf and all the necessary Ansibile files
    vars:
    - ansible_python_interpreter: "{{ '/usr/bin/python3' }}"
    hosts: aix
    gather_facts: false

    tasks:
#      - name: set interpreter to native Python
#        set_fact:
#          ansible_python_interpreter = /usr/bin/python3

      - name: gather facts
        gather_facts:

      - name: increase file systems
        community.general.aix_filesystem:
          filesystem: "{{ item }}"
          size: 20G
          state: present
        loop:
          - /tmp
          - /var
          - /opt

      - name: increase paging space
        community.general.aix_lvol:
          vg: rootvg
          lv: hd6
          size: 3G
          state: present

      - name: copy resolv.conf
        copy:
          src: /etc/resolv.conf
          dest: /etc/resolv.conf

      - name: copy profile file
        copy:
          src: profile
          dest: /.profile

      - name: validate DNF file
        stat:
          path: "/opt/freeware/bin/dnf"
        register: dnf_file

      - name: copy dnf script
        copy:
          src: dnf_aixtoolbox.sh
          dest: /tmp/dnf_aixtoolbox.sh
          owner: root
          group: system
          mode: 0744
        when: not dnf_file.stat.exists

      - name: run install dnf script
        shell:
          cmd: "/tmp/dnf_aixtoolbox.sh -d"
        when: not dnf_file.stat.exists

      - name: set interpreter to newly installed Python3
        set_fact:
          ansible_python_interpreter: /opt/freeware/bin/python3

      - name: up data ulimit
        shell:
          cmd: ulimit -s 2097151

      - name: install python3 via cmd to get around memory error
        shell:
          cmd: /opt/freeware/bin/dnf -y install python3

      - name: install Python3 and other packages
        ansible.builtin.dnf:
          name:
            - python3
            - ansible
            - python3-dnf
          state: latest
          update_cache: true

      - name: Upgrade all packages
        ansible.builtin.dnf:
          name: "*"
          state: latest

      - name: Create ansible directory
        ansible.builtin.file:
          path: /ansible
          state: directory

      - name: Copy files
        git:
          repo: https://github.com/BladesOfSteele/ansible
          dest: /ansible
          update: yes
          version: master


          
# remove /etc/resolv.conf
