---
  - name: Install dnf and all the necessary Ansibile files
    vars:
    - ansible_python_interpreter: "{{ '/usr/bin/python3' }}"
    - pkgtype: dnf
    hosts: all
    gather_facts: false
    # Need this to find the git executable in the git module, LANG is an AIX requirement.
    environment:
      PATH: "/opt/freeware/bin:/usr/bin:/etc:/usr/sbin:/usr/ucb:/usr/bin/X11:/sbin:/usr/java7_64/jre/bin:/usr/java7_64/bin"
      LANG: "en_US.UTF-8"
    collections:
      - ibm.power_aix

    pre_tasks:
      - name: Run prep system playbook first"
        include_tasks: 'prep_system.yml'

    roles:
      - power_aix_bootstrap

    tasks:
#      - name: set interpreter to native Python
#        set_fact:
#          ansible_python_interpreter = /usr/bin/python3

      - name: gather facts
        gather_facts:

#  moved to prep_system.yml, since it's required for role
#      - name: increase file systems
#        community.general.aix_filesystem:
#          filesystem: "{{ item }}"
#          size: 20G
#          state: present
#        loop:
#          - /tmp
#          - /var
#          - /opt
#
#      - name: copy resolv.conf
#        copy:
#          src: /etc/resolv.conf
#          dest: /etc/resolv.conf
#
#      - name: copy profile file
#        copy:
#          src: profile
#          dest: /.profile

#      - name: validate DNF file
#        stat:
#          path: "/opt/freeware/bin/dnf"
#        register: dnf_file
#
#      - name: copy dnf script
#        copy:
#          src: dnf_aixtoolbox.sh
#          dest: /tmp/dnf_aixtoolbox.sh
#          owner: root
#          group: system
#          mode: 0744
#        when: not dnf_file.stat.exists
#
#      - name: run install dnf script
#        shell:
#          cmd: "/tmp/dnf_aixtoolbox.sh -d"
#        when: not dnf_file.stat.exists


      - name: set interpreter to newly installed Python3
        set_fact:
          ansible_python_interpreter: /opt/freeware/bin/python3

#      - name: install python3 via cmd to get around memory error
#        shell:
#          cmd: /opt/freeware/bin/dnf -y install python3

      - name: install Python3 and other packages
        ansible.builtin.dnf:
          name:
            - python3
            - ansible
            - python3-dnf
            - git
            - python3-jmespath
          state: present
          update_cache: true

      - name: Upgrade all packages
        ansible.builtin.dnf:
          name: "*"
          state: latest

      - name: Create ansible directory
        ansible.builtin.file:
          path: /ansible
          state: directory

      - name: Pull Ansible playbooks from GIT
        git:
          repo: https://github.com/BladesOfSteele/ansible
          dest: /ansible
          update: yes
          version: master

# remove /etc/resolv.conf
      - name: remove /etc/resolv.conf
        file:
          path: /etc/resolv.conf
          state: absent
